//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barbearia.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesGerarMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesGerarMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Barbearia.Domain.Resources.ResourcesGerarMessages", typeof(ResourcesGerarMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BARBEARIA DO {0}.
        /// </summary>
        public static string BARBEARIA_DO {
            get {
                return ResourceManager.GetString("BARBEARIA_DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crédito.
        /// </summary>
        public static string CREDITO {
            get {
                return ResourceManager.GetString("CREDITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DATA {
            get {
                return ResourceManager.GetString("DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Débito.
        /// </summary>
        public static string DEBITO {
            get {
                return ResourceManager.GetString("DEBITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string DESCRICAO {
            get {
                return ResourceManager.GetString("DESCRICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinheiro.
        /// </summary>
        public static string DINHEIRO {
            get {
                return ResourceManager.GetString("DINHEIRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturado em {0}.
        /// </summary>
        public static string FATURADO_EM {
            get {
                return ResourceManager.GetString("FATURADO_EM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pix.
        /// </summary>
        public static string PIX {
            get {
                return ResourceManager.GetString("PIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Pagamento.
        /// </summary>
        public static string TIPO_PAGTO {
            get {
                return ResourceManager.GetString("TIPO_PAGTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string TITULO {
            get {
                return ResourceManager.GetString("TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string VALOR {
            get {
                return ResourceManager.GetString("VALOR", resourceCulture);
            }
        }
    }
}
