//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barbearia.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Barbearia.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data precisa ser anteior a data atual..
        /// </summary>
        public static string DATA_PRECISA_SER_ANTERIOR_A_ATUAL {
            get {
                return ResourceManager.GetString("DATA_PRECISA_SER_ANTERIOR_A_ATUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email já existe..
        /// </summary>
        public static string EMAIL_JA_EXISTE {
            get {
                return ResourceManager.GetString("EMAIL_JA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email e/ou senha inválidos..
        /// </summary>
        public static string EMAIL_OU_SENHA_INVALIDOS {
            get {
                return ResourceManager.GetString("EMAIL_OU_SENHA_INVALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email digitado é inválido..
        /// </summary>
        public static string EMAIL_USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email é obrigatório..
        /// </summary>
        public static string EMAIL_USUARIO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturamento não encontrado..
        /// </summary>
        public static string FATURAMENTO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("FATURAMENTO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email é inválido..
        /// </summary>
        public static string NOME_USUARIO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("NOME_USUARIO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha deve ter no mínimo 8 caracteres, contendo pelo menos uma letra maiúscula, uma letra minúscula, um número e um caractere especial (exemplo: !, ?, @, *).
        /// </summary>
        public static string SENHA_USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("SENHA_USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Pagamento Inválido..
        /// </summary>
        public static string TIPO_PAGTO_INVALIDO {
            get {
                return ResourceManager.GetString("TIPO_PAGTO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título é obrigatório..
        /// </summary>
        public static string TITULO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("TITULO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor precisa ser maior que zero..
        /// </summary>
        public static string VALOR_PRECISA_SER_MAIOR_QUE_ZERO {
            get {
                return ResourceManager.GetString("VALOR_PRECISA_SER_MAIOR_QUE_ZERO", resourceCulture);
            }
        }
    }
}
